### ISSUE TITLE
Some wierd hydration error

### ISSUE THREAD

**Issue by sharmapukar217** [rakkasjs/rakkasjs#55] opened 2022-09-25 16:25 UTC
I tried few headless/aria supported libraries and i got some wierd hydration error: `Warning: Prop `id` did not match. Server: "headlessui-disclosure-button-:Ra:" Client: "headlessui-disclosure-button-:R2:"`.
I even tried those with nextjs to see if that issue was with react18 or maybe the library themself but all worked well with nextjs.
Some of the libraries I used were: @headlessui/react, @radix-ui, @reach-ui, ariakit but i got similar issue. 😞

**Comment by cyco130** [comment] 2022-09-25 17:15
I know it's a drag but can I have a small reproduction please? :)

**Comment by sharmapukar217** [comment] 2022-09-25 17:19
> I know it's a drag but can I have a small reproduction please? :)

oh of course. I'll provide you in a while 😄

**Comment by sharmapukar217** [comment] 2022-09-25 17:37
here [open in codesandbox](https://codesandbox.io/p/github/sharmapukar217/rakasjs-with-headless-libs/csb-0ku1io/draft/small-sky?workspace=%257B%2522activeFileId%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522cl8hmeq6t00072v6lfq4x1wie%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl8hmfgnf004v2v6lxk473mx9%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

or [see repo](https://github.com/sharmapukar217/rakasjs-with-headless-libs)

**Comment by sharmapukar217** [comment] 2022-09-25 17:37
here [open in codesandbox](https://codesandbox.io/p/github/sharmapukar217/rakasjs-with-headless-libs/csb-0ku1io/draft/small-sky?workspace=%257B%2522activeFileId%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522cl8hmeq6t00072v6lfq4x1wie%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl8hmfgnf004v2v6lxk473mx9%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

or [see repo](https://github.com/sharmapukar217/rakasjs-with-headless-libs)

**Comment by cyco130** [comment] 2022-09-26 08:58
It was caused by Rakkas rendering a slightly different tree on the server than on the client which in turn caused `React.useId` to return mismatched strings. Fixed in `0.6.2-next.4` (install `rakkasjs@next`): https://stackblitz.com/edit/github-1ymsd8?file=package.json

Thanks for reporting!

**Closed by cyco130** 2022-09-26 08:58 UTC
