### ISSUE TITLE
Severe HMR lag when using AntD

### ISSUE THREAD

**Issue by khalibloo** [rakkasjs/rakkasjs#57] opened 2022-10-03 06:53 UTC
When using even a single component (say a button) from ant design, Rakkas becomes terribly slow in development. A page refresh could take up to 20 seconds or more. I'm able to use other UI frameworks like Mantine, just fine.

To reproduce, simply create a fresh Rakkas app and install antd. Then import Button and use it on the page.

**Comment by cyco130** [comment] 2022-10-03 07:17
Hi,

I can't reproduce that, everything works fine for me as in this example: https://stackblitz.com/edit/github-jmvvn5?file=src%2Froutes%2Findex.page.jsx

On the first run, Vite optimizes the `antd` dependency, which takes a few seconds but I don't experience any lag other than that. Also we use `antd` at work, so I would know if there was a general problem. It must be something else. Can you provide a reproduction?

**Comment by khalibloo** [comment] 2022-10-03 08:07
You may be on to something. I just tried the same project on a different machine (with similar specs), and it performs just fine. Seems like a system-level issue. Maybe my antivirus is interfering.

**Comment by cyco130** [comment] 2022-10-03 08:15
Closing the issue. Feel free to reopen if it turns out to be related to Rakkas in the end.

**Closed by cyco130** 2022-10-03 08:15 UTC
